

export const detailedWritings = [
  {
    id: 1,
    title: 'Materia',
    content: `Në veprat e disa artistëve, si p.sh. Abramishvili, ky proces i vjetërimit të veprës kthehet në një motiv për krijimin e veprave të reja që ngjajnë si të vjetra. Edhe unë kam bërë një kërkim të ngjashëm në një periudhë si piktor, duke imituar nxirjen e ikonave të vjetra. Por, pavarësisht këtyre rasteve, nuk është ky motivi që i shtyn njerëzit drejt një qasjeje ndaj materies.
              Materia ruan misteret e veta dhe krijon ide përmes vetë proceseve të saj.Pra, jo çdo gjë vjen prej botës së ideve për t’u materializuar; idetë mund të ndryshojnë formë për shkak të materies dhe proceseve që ndodhin mbi të.Arsye të tjera lidhen me formulat e përgatitjes së murit, bojërave, dhe teknikave që duam të ruajmë, të cilat janë mistere të tjera të materies, por më pak të rëndësishme për artistin, pasi ai mund të gjejë një teknikë të re për të arritur një rezultat të ngjashëm.
              Ndoshta qasja e ruajtjes së materies ka të bëjë me një lloj supersticioni magjik ose besimi se materia e përdorur për krijimin e një vepre artistike nuk duhet kurrsesi të pësojë ndryshime, sepse do të humbasë energjinë fillestare dhe peshën që koha ka ushtruar mbi të.Njëlloj siç nuk përpiqemi të bëjmë të njëjtën gjë me trupat e të vdekurve, nuk ndërhyjmë as në veprat e artit për të respektuar jetën e tyre ashtu siç ka qenë.
              Në përfundim, diskutimi mund të shtrohet edhe kështu: Gjëja më e rëndësishme është që vepra e artit të duket ashtu si artisti ka vendosur të duket, apo do t’i atribuojmë veprës një jetë të vetën, ku, pas daljes nga dora e artistit, ajo ka një pavarësi të sajën? Nëse do të bëjmë një analogji që artistët e bëjnë shpesh — që veprat e tyre janë si fëmijët e tyre — atëherë është tjetër gjë dëshira e prindit për të ardhmen dhe tjetër gjë aspiratat e vetë fëmijës.Nga ana tjetër, veprat nuk kanë dëshira si fëmijët, ose të paktën jo aq të artikuluara, por ato janë pjesë e Zeitgeist- it(frymës së kohës) dhe, nën ndikimin e kësaj fryme, marrin jetë ose vdesin.Veprat janë pjesë e trupit të këtij Zeitgeist - i dhe prej tij ato zhvillojnë jetën dhe vdekjen e tyre.Është gjithashtu kjo frymë që përcakton dhe qasjen ndaj plakjes së tyre.Fryma e kohës sot refuzon disi plakjen dhe vdekjen si procese normale të jetës dhe, për rrjedhim, zgjedh qasjen e ruajtjes ekstreme të materies origjinale të veprave, njëlloj si kjo frymë nxit tek njerëzit ndërhyrje të shumta në trupin e tyre për të dukur sa më të rinj.`,
    slug: 'materia'
  },
  {
    id: 2,
    title: 'Memory',
    content: `I often think about how strange memory is. A phenomenon that gives longevity to something that dies moment by moment. A movement, a word, a feeling that was there briefly. It had no intention of stopping, staying, or speaking. But you found it and made it speak, made it stay, gave it a long life within you. Memory, then, grants life. In a new form, fuller and more complete.
              Memory isn’t just about extending the existence of something, but about bringing things, events, and people back to life. Memory gives them true life, beyond the ordinary. What would autumn be without the paintings, the music, the poetry that are born when it passes through our memory? Perhaps a yearly death, a departure from earthly life. But Vivaldi’s autumn gives it true life, the promised and eternal life.
              Memory is also a judge of reality. It decides what deserves to live and what must die, because only what remains within it will continue to live. Everything else will drown in the abyss of forgetfulness. Humans, as beings, do not live on the plane of animals, who live or die moment by moment, inevitably followed by oblivion. Humans live in the world of memory, in the world of true life. Perhaps, when described in the Book of Genesis, the creation of man from clay, and the breath of God entering his nostrils to give him life, is in essence, memory. And the forgetting of God’s command brings death, a departure from true life.
              Memory holds within it both joy and pain, good and bad. It makes a different kind of judgment, not simply between good and evil, but between what is important and what is not. The good serves as fuel for the continuation and motivation of life, while the bad transforms into a lesson, thus turning into something good—if you allow it to.
              Memory, then, is the presentation of eternity in this imperfect plane dominated by death. Memory overcomes the ordinary, filters the river of life, and makes it more perfect. Memory is a sacred gift, showing us what is important and what is not. Its language is somewhat unclear to us, and our task is to understand what is a lesson and what is a good gift.`,
    slug: 'memory'
  },
  {
    id: 3,
    title: 'On Beauty',
    content: `Beauty is what we need. It represents the principle of complementarity. Beauty fills the void and creates a wholeness when it comes into contact with being, thus completing it. This is because beauty does not stand apart from the one who perceives it; rather, it changes depending on each person. From the outset, it must be emphasized that it makes no sense to treat beauty as an objective scientific postulate with unchanging principles. Beauty is, above all, a relationship or an interaction between an object or being and its perceiver.
              There are practical ideas about how something can be considered beautiful, such as harmony, symmetry, etc. However, we have seen that these rules are not applicable to every new form of art that emerges. These rules arise from a specific context when a society finds its wholeness in that manifestation of beauty.
              We can compare it to a piece of dessert: when you are full, it seems repulsive because you have no need for it, but when you are hungry, it appears to be the most delicious thing in the world. This ensures the relativity of beauty, which we understand well today. It also ensures the existence of two forms of beauty: the Dionysian and the Apollonian.
              A person raised in a harsh and warlike environment will be more attracted to Apollonian art, as it provides what they lack and fulfills them. Meanwhile, today, in a peaceful environment, art often reflects the ugly, the violent, the irritating, because peace dominates the atmosphere.
              A person will seek dessert until they are satisfied with it. They will not abandon a form of art without first being satisfied by it because they must be nourished by that form.
              From a psychological perspective, if we rely on Jung’s theory of dreams, which have a compensatory function, then beauty has the same function in our lives as dreams do. It brings to our conscious life those aspects that do not manifest but are present. Beauty is what provides wholeness, not wholeness itself.
              In a time when humanity is more pragmatic and rational, the mysterious becomes more attractive, and the opposite also occurs. For example, the explosion of Hellenic philosophy occurred in a superstitious time, while the rise of superstition, such as New Age culture and later the “Woke” movement, occurs at the peak of a rational culture.
              Beauty, in this sense, appears as a compensator for our deepest needs and desires. It is a dream that tells us something about ourselves that we often do not know. Dreams remind us of aspects from the past that we have not overcome or wish to return to, making beauty a mirror of what we lack. However, they rarely warn us or predict the future, inviting us to reflect on ourselves and our experiences.`,
    slug: 'onbeauty'
  },
  {
    id: 4,
    title: 'Western Babylon',
    content: `Anyone familiar with the Judeo-Christian tradition has heard of Babylon, Sodom and Gomorrah, and the Tower of Babel. At the heart of these narratives lies the destruction of the center that unites all people or a culture. Many false gods confront the true one. These false gods manifest in various forms such as the improper use of pleasure, money, power, self-destruction, selfishness, etc.
              It is impossible not to see a parallel between these stories and what has been happening in the West for about two centuries. What we call Freedom, freedom from the unifying culture, is now being opposed to us. Freedom from the community led us to isolation, freedom from Christianity as Faith and culture caused the breakdown of social cohesion. The breakdown of a common language, as in the time of Babel, for the same reason and with the same consequences. The debate and cultural warfare have extended to the most fundamental issues such as: what is a woman and a man; when a person is called a Being in the mother’s womb. But in terms of cultural aspect, this division is seen in issues like: what is considered beautiful and “should art necessarily be beautiful?” etc.
              There are only a limited number of ways to build something, for example, a box. These limitations are the rules. It must have 6 sides, have two and two identical sides, the identical sides must have two and two identical sizes, and all these elements are linked by a single idea, the box. While there are endless ways and reasons to destroy the box, and with its destruction, regardless of any means or reason, the box and its idea, which is certainly indestructible, are sought to be destroyed. There is only one way to give birth to a child and infinitely to kill or die. Regardless of the reasons, death seeks to destroy what is alive. Here, I want to focus because the methods of destroying a culture are perceived as a way to build something new.
              If I were to make an analogy with art, I would say that there are a limited number of ways to make art or something beautiful. And there are endless ways to make deconstructive art, such as abstraction, conceptual art, etc. As a conclusion, what happens is the destruction of the language of communication that figurative art establishes (here I do not want to deny the healing aspect that these forms may have individually). This reminds us of the archetypal story of Osiris being fragmented by Seth, and Isis remaining pregnant with the collected parts of Osiris to give birth to Horus, who will revitalize the kingdom by driving out evil.
              Classical art is fragmented by evil, so is academicism, like a kind of anxiety and fear of death, while abstract and deconstructivist art does not represent Seth but Isis. Isis is the part of chaos that feeds the son with formless energy, gives him the necessary material to revitalize what was damaged, Osiris. But if you do not know Osiris (the root from which tradition comes), then you will simply be filled with energy but without direction. Horus is consciousness, Osiris is direction, and Isis is energy, while Seth is evil or entropy.
              Evil has already been done, in Western civilization, tradition has been fragmented, it has become a relic. Chaos has overflowed, trying everything, every form of art without direction, without tradition, without values, exploring values and anti-values. The new one that will be born must renew tradition but with new energy.
              Agents of culture (artists, academics, musicians, writers, etc.) lack objective vision today because their god is not the God who is Heaven, but the god created by their hands. Today they live in what is called Ego-drama. The emphasis is always on oneself, my experience, my right, my creation; I even have to come up myself with an Idea of what god is and this is widely welcomed and celebrated without questioning the foolishness of that undertaking. This focus ensures the fragmentation of culture into very small and powerless units, produces an art that does not feed your hunger, and quickly fades away and requires very large expenses to maintain its position.`,
    slug: 'westernbabylon'
  },
  {
    id: 5,
    title: 'Mbi te Bukuren',
    content: `E bukura është ajo që kemi nevojë. Ajo përfaqëson parimin e komplementaritetit. E bukura mbush boshllëkun dhe krijon një tërësi kur vihet në kontakt me qenien, pra e plotëson atë. Kjo sepse e bukura nuk qëndron e shkëputur nga ai që e percepton, por ndryshon në varësi të çdo njeriu. Që në fillim, duhet të theksojmë se nuk ka kuptim ta trajtojmë të bukurën si një postulat shkencor objektiv me parime të pandryshueshme. E bukura është, para së gjithash, një marrëdhënie ose një ndërveprim mes një objekti apo frymori dhe perceptuesit të tij.
              Ekzistojnë ide praktike për mënyrën se si diçka mund të konsiderohet e bukur, si p.sh. harmonia, simetria, etj. Megjithatë, kemi parë që këto rregulla nuk janë të vlefshme për çdo formë të re arti që lind. Këto rregulla burojnë nga një kontekst i caktuar, kur një shoqëri e gjen plotësinë e saj në atë shfaqje të së bukurës.
              Mund ta krahasojmë me një copë ëmbëlsire: kur je i ngopur, ajo të duket e neveritshme sepse nuk ke nevojë për të, por kur je i uritur, të duket si gjëja më e shijshme në botë. Kjo siguron relativitetin e bukurisë, të cilin ne sot e kuptojmë mirë. Gjithashtu, kjo siguron ekzistencën e dy formave të bukurisë: asaj dionisiake dhe asaj apoloniane.
              Një person i rritur në një ambient të ashpër dhe luftarak do të tërhiqet më shumë nga arti apollonian, sepse aty gjen atë që i mungon, duke e plotësuar. Ndërsa sot, në një ambient të qetë, arti shpesh reflekton të shëmtuarën, dhunën, irritimin, sepse paqja është dominuesja e ambientit.
              Njeriu do të kërkojë ëmbëlsirën deri sa të ngopet me të. Nuk do ta braktisë një formë arti pa u ngopur më parë me të, sepse ai duhet të ushqehet më parë me atë formë.
              Në aspektin psikologjik, nëse do të mbështetemi te teoria e Jung-ut për ëndrrat, të cilat kanë funksion kompensues, atëherë e bukura ka të njëjtin funksion në jetën tonë si ëndrrat. Ajo sjell në jetën tonë të ndërgjegjshme ato aspekte që nuk shfaqen, por që janë aty. E bukura është ajo që siguron plotësinë dhe jo plotësia vetë.
              Në një kohë kur njeriu është më pragmatik dhe racional, e mistershmja bëhet më tërheqëse dhe e kundërta ndodh gjithashtu. Për shembull, shpërthimi i filozofisë helene ndodhi në një kohë supersticioze, ndërsa rritja e supersticionit, si kultura “New Age” dhe më vonë lëvizja “Woke”, ndodh në kulmin e një kulture racionale.
              E bukura, në këtë kuptim, shfaqet si një kompensues për nevojat dhe dëshirat tona më të thella. Ajo është një ëndërr, e cila na tregon diçka për veten që shpesh e kemi të panjohur. Ëndrrat na kujtojnë aspekte nga e shkuara që nuk i kemi tejkaluar ose që dëshirojmë t’i rikthejmë, duke e bërë të bukurën një pasqyrë të asaj që na mungon. Megjithatë, ato rrallëherë na paralajmërojnë ose parashikojnë të ardhmen, duke na ftuar të reflektojmë mbi vetveten dhe përjetimet tona.`,
    slug: 'mbitebukuren'
  },
  {
    id: 6,
    title: 'Kujtesa',
    content: `E mendoj shpesh sa e çuditshme është kujtesa. Një fenomen që i jep jetëgjatësi diçkaje që vdes moment pas momenti. Një lëvizjeje, një fjale, një gjendjeje që ishte aty kalimthi. Që nuk kishte për qëllim të ndalonte, të qëndronte, të fliste. Por ti e gjete dhe e bëre të flasë, e bëre të qëndrojë, t’i japësh brenda teje një jetë të gjatë. Kujtesa, pra, dhuron jetë. Në një formë të re, më të plotë.
              Kujtesa nuk ka të bëjë thjesht me zgjatjen e ekzistencës së diçkaje, por me sjelljen në jetë të sendeve, ngjarjeve e njerëzve. Kujtesa u jep atyre jetën e vërtetë, përtej së zakonshmes. Çfarë do të ishte vjeshta pa pikturat, pa muzikën, pa poezinë që lind kur ajo kalon përmes kujtesës sonë? Ndoshta një vdekje e përvitshme, një largim nga jeta tokësore. Por vjeshta e Vivaldit i jep asaj jetën e vërtetë, atë të përjetshmen dhe të premtuarën.
              Kujtesa është gjithashtu një gjyqtare e realitetit. Ajo zgjedh çfarë duhet të jetojë dhe çfarë duhet të vdesë, sepse vetëm ajo që mbetet brenda saj do të vazhdojë të jetojë. Gjithçka tjetër do të mbytet në humnerën e harresës. Njeriu, si qenie, nuk jeton në rrafshin e kafshëve që jetojnë ose vdesin moment pas momenti, ndjekur pashmangshmërisht nga harresa. Njeriu jeton në botën e kujtesës, në botën e jetës së vërtetë. Ndoshta, kur përshkruhet në Librin e Zanafillës krijimi i njeriut prej balte, fryma e Perëndisë që i futet në vrimat e hundës për t’i dhënë jetë është në vetvete kujtesa. Dhe harresa e urdhrit të Perëndisë sjell vdekjen e tij, largimin nga jeta e vërtetë.
              Kujtesa mban brenda lumturi dhe dhimbje, të mira dhe të këqija. Ajo bën një lloj tjetër gjykimi, jo thjesht ndërmjet të mirës dhe të keqes, por ndërmjet të rëndësishmes dhe të parëndësishmes. E mira shërben si karburant për vazhdimin dhe motivimin e jetës, ndërsa e keqja transformohet në një mësim, pra kthehet në një të mirë, nëse ti e lejon të kthehet në këtë të mirë.
              Kujtesa, pra, është prezantimi i përjetësisë në këtë rrafsh jo të përsosur, të dominuar nga vdekja. Kujtesa mposht të zakonshmen, filtron gjithë lumin e jetës dhe e bën atë më të përsosur. Kujtesa është një dhuratë e shenjtë, që na tregon se çfarë është e rëndësishme dhe çfarë jo. Gjuha e saj është disi e paqartë për ne, dhe detyra jonë është të kuptojmë se çfarë është një mësim dhe çfarë është një dhuratë e mirë.`,
    slug: 'kujtesa'
  },
];